### ISSUE TITLE
This campaign has bug: D-Day Omaha beach.

### ISSUE THREAD

**Issue by daviddogtw** [nicupavel/openpanzer#224] opened 2019-05-22 16:33 UTC
Why Flak38 is here? I can't control this unit, so I think it must be a bug...
![2019-05-23](https://user-images.githubusercontent.com/50922695/58191797-ec9a2b80-7cf1-11e9-97da-907b8672bee1.png)
#bug

**Comment by salexgit** [comment] 2019-05-23 02:28
Hi

If you open this scenario in e.g. Web version or on a desktop, you will see that there is a cruiser in that location. It looks similar to the problem reported in #199. If the game fails to load the equipment file, some/all units are shown as Flaks. The next game version will hopefully fix it... 

Meanwhile, one way to circumvent around the problem is to open a saved game from the previous scenario in e.g. Web version and start D-Day scenario there.  

Regards, Alex

**Comment by nicupavel** [comment] 2020-10-19 14:22
This should be fixed in latest versions

**Closed by nicupavel** 2020-10-19 14:22 UTC
