### ISSUE TITLE
Computer turn crash/freeze 

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#231] opened 2019-06-25 13:21 UTC
I came across this problem while testing the beta, the ai starts his turn but then is unable to finish it.
Can something be done about it?
I  have especially problems with the Malta scenario in the Italian campaign.
Ps. For some reason I’m not able to attach the file of the scenario

**Comment by salexgit** [comment] 2019-06-26 12:31
Hi

You can attach the saved game here by compressing it with e.g. zip archiver. Do please send us the saved game.

**Comment by campaignbuff** [comment] 2019-06-26 13:26
Tried...

**Comment by campaignbuff** [comment] 2019-06-27 10:38
I’m still not able to send the scenario, I’m currently playing the beta on line on a mobile device (iPad pro).
GitHub for some reason doesn’t accept the format

**Comment by salexgit** [comment] 2019-06-27 10:51
Hi

GitHub does not allow uploading .json file formats, but you can compress it and upload .zip file.

**Comment by eitzenbe** [comment] 2019-06-30 11:10
Attached is Malta turn 4, after pressing end turn the AI does not finish its turn
[malta.zip](https://github.com/nicupavel/openpanzer/files/3342796/malta.zip)

**Comment by salexgit** [comment] 2019-06-30 12:23
Hi

Thanks for providing the saved game.
It seems that there is a hidden victory hex - I cannot say now for sure whether it is intentional or not. If you start a new Malta scenario, you will see that remaining number of objectives is 2, whereas the strategic map will map only one victory hex.
I will check the scenario asap and will let you know where that hidden victory hex is, if this is a real problem.

Regards, Alex

**Comment by campaignbuff** [comment] 2019-06-30 13:10
Hi, sorry for my absence
I don’t have really understood the answer, in the meantime I might be able to find a way to show you the scenario in the form of cloud save:
c8eedc99baffe7dbd1cb0725283fb93a
If you can still help...
Thanks in advance

**Comment by salexgit** [comment] 2019-07-01 10:34
Hi

For @eitzenbe and @campaignbuff, it seems that there is a clash of comments. You are both commenting on the Malta scenario, but from different campaigns. Saved game from @eitzenbe is for the German campaign, while @campaignbuff cloud save is for the Italian campaign.
It could be the case that the issues are completely different because having the same Malta map does not mean that the objectives are the same. I will double check saved game and, if needed, will split this issue into separate threads.

Regards, Alex

**Comment by campaignbuff** [comment] 2019-07-01 12:41
Hi Alex,
With all respect to the other user, I opened this thread specifically to address the crash problem in the Italian campaign, there has been a misunderstanding... the problems are indeed completely different, @eitzenbe came out of the blue with a problem that deserves his own issue.

**Comment by salexgit** [comment] 2019-07-01 13:55
Hi

No offence to anybody... I will try to sort out these issues and instantiate if needed a separate thread for the problem report by @eitzenbe. Let's just keep in mind that we are dealing with two different Malta scenarios.

**Comment by salexgit** [comment] 2019-07-01 18:56
Hi again

I have to take my words back - even though the scenarios are different, there can be the same root cause. In fact, it seems that the problem is the same as was reported in #226. 
I will talk to the main developer because the problem is not with the scenario but rather with how the game engine handles certain units types. The common denominator across all the problems is presence of the carrier unit type. 

Regards, Alex

**Comment by nicupavel** [comment] 2019-09-22 06:43
Found the culprit should be fixed in 3.2.6

**Closed by nicupavel** 2019-09-22 06:43 UTC
Labels: bug
