### ISSUE TITLE
The Fourth Battle for Kharkov

### ISSUE THREAD

**Issue by shidia** [nicupavel/openpanzer#49] opened 2014-10-28 14:45 UTC
This scenario has 2 objectives required for victory that do not appear on the map during the German campaign.  The city in the upper left hand corner and there is a Russian unit in the woods on the right hand side that must be destroyed for victory.  Even though there is no flag on either hex if you take these it completes the scenario.

**Comment by salexgit** [comment] 2018-09-06 02:17
Hi all

Having played this scenario, "The fourth battle for Kharkov" from the DasReich campaign, I noticed that the problem is still there even though it has been reported four years ago. As reported in the original post, the problem is that there are two objectives which are not displayed at all on the map. 

Having delved into testing this scenario, I realized that the game engine does not render the victory hex if no flag is assigned to it. And this is exactly what happens in this case - for some reason two victory hexes do not have assigned flags and the game does not display them at all effectively creating hidden victory hexes. I am not entirely sure whether it is the intended behavior, at least in this scenario. The matter is that the same problem exists also for the Soviet player - German hexes to conquer are not displayed either for exactly the same reason. This is in fact very confusing also for the Germany player as he does not know which hexes it has to protect.

I applied fixes by simply assigning flags to all the victory hexes. As you can see from the attached snapshot, now the game engine displays properly 2 victory hexes for a German player and 6 victory hexes for a Soviet player (please note that the snapshot was taken with the summer map as discussed in #141 ).

![drkhar23](https://user-images.githubusercontent.com/22852936/45130819-efb8b000-b192-11e8-84bc-688340744f01.png)

If I have time, I will provide fixed .SCN file for this scenario.

By the way, I am not sure why Germans have to conquer hex at (28,42), i.e. at the right hand side of the map. According to history, main battles took place north-west from Kharkov closer to Bogodukhov, while the German army was in the defensive stance on the south-east direction.  DasReich and other panzer divisions were not (counter-)attacking on that direction.

Regards, Alex

**Comment by salexgit** [comment] 2018-09-07 09:42
Hi again

Here is the fixed .SCN file for this scenario, in which flags have been assigned to all the victory hexes. Hopefully that will make this scenario easier to play.

[drkhar23.scn.zip](https://github.com/nicupavel/openpanzer/files/2360495/drkhar23.scn.zip)

I converted this .SCN file into .XML format and checked by "diff" that the only change is the flag parameter applied to the corresponding tiles. 

Regards, Alex

**Comment by nicupavel** [comment] 2018-09-07 09:47
Thanks ! You can commit to staging-changes-old branch on bitbucket. 
As for historical accuracy, these scenarios are semi-accurate probably this is how the campaign designer saw fit.

**Comment by salexgit** [comment] 2018-09-08 06:50
Hi

Ok, I will commit these changes to make the scenario more transparent. 
The only reason why the original campaign designer might have considered adding hidden victory hexes is to make it as a defensive scenario: you cannot win it, but rather you have to defend what you have for X turns. However, it does not explain either why German victory hexes were not assigned any flag - you need to know what you have to protect. 

If I have time, I might take a look at this scenario in the original Panzer game. Maybe it will provide more clues on what the anticipated behavior should be.

**Comment by nicupavel** [comment] 2018-09-28 05:38
Fixed in 2.9.8

**Closed by nicupavel** 2018-09-28 05:38 UTC
Labels: scenario
