### ISSUE TITLE
Scenario and Campaign Enhancements Please

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#129] opened 2017-09-06 01:48 UTC
Great game. Using Open Panzer beta I have been able to work around the issues and finish all of the campaigns. That is the issue. Would like some additional scenarios in the existing campaigns or new campaigns. Alternatively, the existing scenarios could be modified to create fresh and/or more difficult challenges. Or alternatively, a random element generator can be added to increase the size and vary the location of AI units. Finally, game could allow player to play both siides to manually which would allow for stronger defense than AI can put together. ANY ENHANCEMENT WOULD BE TERRIFIC!!

**Comment by salexgit** [comment] 2017-09-07 13:10
If you want to have a huge number of nations, campaigns and scenarios, then consider OpenGeneral. You can play it also locally.

I have been thinking of making OpenPanzer to understand OpenGeneral formats so that the former can leverage OpenGeneral scenarios, but I have no idea how big work it would be. Definitely it is not a trivial change. However, the idea is neat as we would run the OpenPanzer engine on top of the OpenGeneral maps and equipment files :)

**Comment by Cjh1953** [comment] 2017-10-08 16:56
Thanks for the suggestion. That said, I don't think open general runs on iPads.

**Comment by salexgit** [comment] 2017-10-09 10:52
Hi

OpenGeneral has been written for Windows platform and I was able to run it under Linux in "wine". However, I have no idea whether it would be a big excercise to port it to Apple and Android platforms.

In fact, that is the beauty of this project as it runs on any platform. And is that is why one of the approaches to keep it alive is to make it as add-on on top of the OpenGeneral scenarios and equipment files.

**Comment by salexgit** [comment] 2017-12-05 12:30
@Cjh1953 In case you are interested in new campaigns and testing them, check #136. I would be grateful if somebody plays it and provides the feedback.

**Comment by salexgit** [comment] 2020-01-16 11:12
The issue is closed as we use to have a separate issue/discussion thread for every new campaign we add.

**Closed by salexgit** 2020-01-16 11:12 UTC
Labels: enhancement
