### ISSUE TITLE
Can't win on 7th French Army rush North

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#148] opened 2018-10-10 23:34 UTC
I've captured all the French towns, I never even lost one, I've wiped out ever French unit including the damn ship and yet it will still not let me win.
This is really annoying. I now can't get a brilliant victory? I will not resume the campaign till that's fixed because I don't think it's right that I'm missing out on units for something I didn't do.

**Comment by LaughtersGrave** [comment] 2018-10-10 23:34
I don't know how to attach screen shots, there's no button for it :/

**Comment by salexgit** [comment] 2018-10-11 01:20
Hi

Can you please elaborate on what happens exactly? Do you mean that you capture all the victory tiles but the game engine does not let you win? There was a bug in the past when the game engine was doubling number of objectives, but it was fixed.
 
If possible, can you please attach the saved game _before_ you capture the last vicotry hex?

Regards, Alex

**Comment by LaughtersGrave** [comment] 2018-10-11 07:45
How do I attach the file?

**Comment by nicupavel** [comment] 2018-10-11 08:07
Use save to cloud from the game and copy/paste the ID here.

**Comment by salexgit** [comment] 2018-10-11 08:12
Hi LaughtersGrave

To attach and send the saved game, compress .json file and attach the resulting .zip file here. GitHub will allow you to attach .zip files.

**Comment by LaughtersGrave** [comment] 2018-10-11 08:34
There is no game save where there are uncaptured major cities, on 7th French Army North Rush map you start with them all. I lost none. The French game 4 minor cities I captured all these but it still says they're 3 objectives.

Anyways, here's the cloud ID
9c2bdba16be204673f5fd02b0b2ce87b

**Comment by LaughtersGrave** [comment] 2018-10-11 15:54
Any idea?

**Comment by LaughtersGrave** [comment] 2018-10-12 15:05
Any help guys?

**Comment by LaughtersGrave** [comment] 2018-10-14 01:32
I didn't have a first turn but a turn 3 shows this
![screenshot_2018-10-14-02-25-58-889_com ecosia android](https://user-images.githubusercontent.com/44041995/46911593-d73d7180-cf58-11e8-8947-fdb135572c18.png)
3 objectives. 

HOWEVER if you examine the map there are NO objectives
![screenshot_2018-10-14-02-26-46-940_com ecosia android](https://user-images.githubusercontent.com/44041995/46911599-f9cf8a80-cf58-11e8-86df-63eccba314c8.png)

And in the normal operations window that you're in by default there are clearly only 3 MINOR towns, no MAJOR objectives at all

![screenshot_2018-10-14-02-26-30-391_com ecosia android](https://user-images.githubusercontent.com/44041995/46911609-2edbdd00-cf59-11e8-9e2f-974ebb01c970.png)

I. Thought the objective might be to wipe out three groups of French Army but as you saw in the cloud file I had annihilated everything in the map and the every point that you can capture. 

I don't know what to do.

**Comment by salexgit** [comment] 2018-10-14 02:30
Hi again

I checked victory hexes, they are as follows: (0,1), (27,32), (37,1). Note that (0,1) is in the open sea so you cannot win the scenario, even if you take (27,32), (37,1). However, I recalled that I was playing this scenario in 2.9.7 and I did not have any issue at all. So, I opened 2.9.7 and realized that in 2.9.7 this scenario has only one objective at (35,17).

What happened is that we regenerated the whole DasReich campaign from the original SCN files. It seems that original SCN files had some issues which were fixed in 2.9.7, but which we forgot to re-apply again.

@nicupavel Can you please mark this thread as "scenario, bug"? I can fix it by making the corresponding changes to the SCN file.

**Comment by salexgit** [comment] 2018-10-15 05:03
If nothing goes wrong and if there are no changes affecting saved games, you should be able to load your game and win :)

**Comment by LaughtersGrave** [comment] 2018-10-15 17:42
@Lutarp 
there's a patch?

**Comment by LaughtersGrave** [comment] 2018-10-15 17:43
Whoops sorry

**Comment by LaughtersGrave** [comment] 2018-10-16 19:46
@Lutarp you have a patch?

**Comment by Lutarp** [comment] 2018-10-16 19:48
No

**Comment by LaughtersGrave** [comment] 2018-10-16 19:50
Oh, OK. Ty

**Comment by salexgit** [comment] 2018-10-17 04:38
Hi all

I was on a business trip and did not have time to fix it. The correction should be quite simple - we already applied it once to another scenario which had a similar problem. 
I will let you know later today whether it works. Then I will discuss with the main developers whether we can release asap a new version containing this fix.

**Comment by Lutarp** [comment] 2018-10-17 09:35
Is it just this fix, or will a future patch also fix the corrupted game
path?

On Oct 17, 2018 00:38, "salexgit" <notifications@github.com> wrote:

Hi all

I was on a business trip and did not have time to fix it. The correction
should be quite simple - we already applied it once to another scenario
which had a similar problem.
I will let you know later today whether it works. Then I will discuss with
the main developers whether we can release asap a new version containing
this fix.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nicupavel/openpanzer/issues/148#issuecomment-430486938>,
or mute the thread

**Comment by salexgit** [comment] 2018-10-17 22:02
Hi all

I have fixed the problem, as you can see from the attached screenshot - there is only one objective  which is explicitly displayed on the map. In short, it is exactly the same behavior as it was in 2.9.7. I will check with main developers when we can push this change to the official version.

![9fr](https://user-images.githubusercontent.com/22852936/47118685-c2baeb00-d270-11e8-8da6-99b076708d7c.png)

@LaughtersGrave Unfortunately, you will have to replay the whole scenario. Currently the game is designed in such a way that the saved game effectively contains a copy of the MAP and SCN information including all the victory hexes. So, your saved game has old information for victory hexes :/

@Lutarp This email thread is only for this problem. Corrupted game patch will be announced and discussed on the corresponding discussion thread.

**Comment by LaughtersGrave** [comment] 2018-10-17 22:19
@salexgit 
So do I just play scenario again or do I have to download something?
Assuming that you have to just replay the scenario of I didn't have a save that far back I assume I have restart the entire campaign yes?

Lastly, 
When the transports issue in my other thread gets fixed, will I have to start a scenario or the whole campaign again, again?

**Comment by salexgit** [comment] 2018-10-17 23:43
Hi

You have to wait till I post on this thread whether a new official version is available and/or whether there is another way to play your scenario circumventing around the problem you have. Sorry for a delay and all the inconveniences... 
As a common practice, I do recommend to have saved games at least at the scenario end before you take the last victory hex. Then, it will be easier to replay a scenario without starting again the whole campaign. 

Regarding the transport issue #147 being discussed on in a different thread, let's discuss it there without mixing together all the topics. I personally did not look into that issue, but my feeling is that it is a purely game engine problem. Furthermore, it affects only a limited set of units - so far it is only the Flak unit where this problem was spotted. So maybe it is the intentional behaviour governed by some unit's attributes.

**Comment by salexgit** [comment] 2018-10-21 09:29
Hi all

As a small status update, I checked all the scenarios in the DasReich campaign and noticed that another scenario, "Typhoon called off", has a similar issue. I fixed both scenarios and the corresponding changes are already committed to the main development branch. So, the next version of the game will include all these corrections.

**Comment by LaughtersGrave** [comment] 2018-10-21 10:48
When do you think the next update will be released? And will the browser version be released at the same time? I've had some weird issues with the app

**Comment by LaughtersGrave** [comment] 2018-10-24 23:45
Oh the app issue thing is that after finishing a mission when I save anywhere after starting the second mission the save from the second mission will not load, it simply continues from exactly where you are and if you then load an older save from mission one then try to load the save from mission two, it simply carries on in mission one exactly as if you'd pressed continue game rather than load

**Comment by salexgit** [comment] 2018-10-25 01:50
Hi LaughtersGrave

Since the issue you described is a new one, can you please open a new issue? Can you please also indicate whether it is for Android or iOS? 
It would be also nice to have a saved game with which we can reproduce the problem. Can you please attach the one and/or provide the saved game ID?

**Comment by salexgit** [comment] 2018-10-26 00:50
Hi LaughtersGrave

Online beta 2.9.9 has been released in which this issue has been fixed:
http://openpanzer.net/beta/

**Comment by LaughtersGrave** [comment] 2018-10-26 12:39
@fallen262 
I found that too, about the hexes in student all being swamp around your core units. I thought it was deliberate to make you play with the paras provided.

All terrain units, tracked, and half tracked move fast over these. If you're infantry is in trucks it's quicker to have them on foot. Leg units can move 2 hexes in swamp.

**Comment by LaughtersGrave** [comment] 2018-10-26 12:46
Ok so I openpanzer beta on my browser and attempted to load from disk. Just like fallen it goes right to minorca tutorial and then I can't do anything.

Going to save to cloud and try loading that way now

**Comment by LaughtersGrave** [comment] 2018-10-26 12:51
Nope, that just takes me to minorca too

**Comment by LaughtersGrave** [comment] 2018-10-26 19:29
Ok. It seems to be working now.

Student map still has the swamp hexes marked in the south with the rail line making no difference. 
![screenshot_2018-10-26-17-34-42-781_com ecosia android](https://user-images.githubusercontent.com/44041995/47588307-a8ae9600-d95d-11e8-933a-f913ed8202fc.png)

**Comment by salexgit** [comment] 2018-10-26 23:31
Hi all

Just for information, the game does not support the concept of railroads and MAP files know nothing about them. In other words, even though you can see railroads, they do not mean anything (unless they are marked internally as roads). 

Coming back to the MAP file for the Student scenario, I checked map and noticed that some hexes have wrong terrain information. Strangely enough, 2.9.7 had correct terrain data. As an example, hex (33,40) had "road" attribute allowing you to cross the river in this point, but it is not possible in 2.9.8. It seems that we unintentionally used old(-er) MAP file.

I will open a new issue and we will try to fix it asap.

**Comment by nicupavel** [comment] 2018-11-01 16:12
Fixed in 2.9.9-2

**Closed by nicupavel** 2018-11-01 16:12 UTC
Labels: bug, scenario
