### ISSUE TITLE
Vienna Victory Conditions

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#107] opened 2017-01-20 23:12 UTC
the German forces have captured all the major victory locations and all of the minor ones too but victory does not occur. Is there a secret victory location? Or is the location in the one inaccessible location boundaried by mountains? Great game overall.

**Comment by marcofango** [comment] 2017-01-26 16:24
Curious about that too.
If you take a look inside any saving of your game, you see there's a field named "sidesVictoryHexes".
That field is splitted for both the players: some hex for player 0, some for player 1.
In Vienna victory hex is located in row 2, column 24, but you cannot reach it by earth.

**Comment by nicupavel** [comment] 2018-09-28 06:02
The scenario was designed to be played with Russia in the Great Patriotic War campaign. Probably can be fixed by adding an actual victory hex for Germans.

**Comment by salexgit** [comment] 2020-01-09 13:10
Hi all

There is a hidden victory hex surrounded by escarpments which you cannot reach by earth. This is done intentionally because Vienna was one of the last battles for the German troops, which they did not win and after which they surrendered to US forces. So the scenario just tries to model historical events by making it "not-winnable". 
Maybe the scenario description can be improved a bit to avoid this confusion...

**Closed by salexgit** 2020-01-09 13:10 UTC
Labels: scenario
